"""Add mobile number to User model

Revision ID: d4bd9c920d00
Revises: adf9ee870799
Create Date: 2025-03-05 13:12:28.535543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bd9c920d00'
down_revision = 'adf9ee870799'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('mobile_number', sa.String(length=15), nullable=False, server_default='N/A')
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mobile_number')

    # ### end Alembic commands ###
